- hosts: all
  become: yes
  tasks:

    - name: Install required packages
      apt:
        name:
          - ca-certificates
          - curl
          - gnupg
          - python3-pip
        state: present
        update_cache: yes

    - name: Check if Docker GPG key exists
      stat:
        path: /etc/apt/keyrings/docker.gpg
      register: docker_gpg_stat

    - name: Add Docker GPG key (if missing)
      shell: |
        install -m 0755 -d /etc/apt/keyrings
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
        chmod a+r /etc/apt/keyrings/docker.gpg
      when: not docker_gpg_stat.stat.exists

    - name: Add Docker repository
      shell: |
        echo \
        "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu noble stable" | \
        tee /etc/apt/sources.list.d/docker.list > /dev/null

    - name: Install Docker CE and tools
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present
        update_cache: yes

    - name: Ensure Docker service is started
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Add azureuser to Docker group
      user:
        name: azureuser
        groups: docker
        append: yes

    - name: Install Python Docker SDK (needed for community.docker)
      pip:
        name: docker
      become: yes

    - name: Create directory for app files
      file:
        path: /home/azureuser/hello-world-app/
        state: directory
        owner: azureuser
        group: azureuser
        mode: '0755'

    - name: Copy application files (Dockerfile + index.html) to server
      copy:
        src: ./  # Only copy app folder, not whole repo
        dest: /home/azureuser/hello-world-app/
        owner: azureuser
        group: azureuser

    - name: Build Docker image
      community.docker.docker_image:
        name: hello-world-app
        build:
          path: /home/azureuser/hello-world-app/
        source: build
      become: yes  # Required if Docker group membership not fully applied yet (new user group membership needs logout/login)

    - name: Run Docker container
      community.docker.docker_container:
        name: hello-world-app
        image: hello-world-app
        state: started
        restart_policy: always
        ports:
          - "80:80"
        recreate: true
      become: yes  # Same reason as above
