name: Deploy to Azure VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible sshpass docker.io python3-pip
          pip3 install docker docker-compose

      - name: Configure and Deploy using Ansible
        run: |
          ansible-playbook -i 172.174.72.168, playbook.yml -u azureuser --extra-vars "ansible_ssh_pass=Password1234!" -e 'ansible_ssh_common_args="-o StrictHostKeyChecking=no"'
