name: Deploy to Azure VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Ansible and Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible sshpass python3-pip
          ansible-galaxy collection install community.docker
          pip3 install docker

      - name: Deploy to Azure VM
        run: |
          ansible-playbook -i inventory.ini playbook.yml
